author: tdg5.com
copyright: 'tdg5 &copy; 2015. All Rights Reserved.'
description: Misadventures in programming!
featured_image:
  alt_text: blog.tdg5.com
  title: blog.tdg5.com
  url: /assets/images/favicons/favicon-256.png
google_analytics_id: UA-47215613-1
highlighter: rouge
language: en-US
markdown: redcarpet
name: blog.tdg5.com
permalink: /:title/index.html
pingdom_rum_id: 54e9c078abe53d617dd34388
redcarpet:
  extensions: [
    autolink,
    disable_indented_code_blocks,
    fenced_code_blocks,
    footnotes,
    no_intra_emphasis,
    space_after_headers,
    strikethrough,
    tables,
    underline
  ]
simple_hueman:
  rss_item_limit: 10
social:
  disqus_shortname: tdg5
  facebook_app_id: "1190183924340795"
  twitter_username: dannyguinther
tagline: explore, create, adapt, repeat
title: tdg5
url: http://jekyll.tdg5.com
wordpress_stats_id: 85533364
