author: tdg5.com
copyright: 'tdg5 &copy; 2015. All Rights Reserved.'
description: Misadventures in programming!
featured_image:
  alt_text: blog.tdg5.com
  title: blog.tdg5.com
  url: /assets/images/favicons/favicon-256.png
highlighter: rouge
language: en-US
markdown: redcarpet
permalink: /:title/index.html
redcarpet:
  extensions: [
    autolink,
    disable_indented_code_blocks,
    fenced_code_blocks,
    footnotes,
    no_intra_emphasis,
    space_after_headers,
    strikethrough,
    tables,
    underline
  ]
simple_hueman:
  rss_item_limit: 10
social:
  twitter_username: dannyguinther
tagline: explore, create, adapt, repeat
title: tdg5
url: http://localhost:4000
